# data.py
foods = {
    # 🥩 Proteins - Meat
    "beef (lean)":           {"calories": 250, "state": "cooked", "ar": "لحم بقر"},
    "turkey breast":         {"calories": 135, "state": "cooked", "ar": "صدر ديك رومي"},
    "lamb":                  {"calories": 294, "state": "cooked", "ar": "لحم ضأن"},
    "duck":                  {"calories": 337, "state": "cooked", "ar": "بط"},
    "beef steak":            {"calories": 271, "state": "cooked", "ar": "ستيك لحم"},
    "lamb liver":            {"calories": 139, "state": "cooked", "ar": "كبدة ضأن"},
    "sausage":               {"calories": 301, "state": "cooked", "ar": "سجق"},
    "smoked turkey":         {"calories": 104, "state": "cooked", "ar": "تركي مدخن"},
    "salmon":                {"calories": 208, "state": "cooked", "ar": "سلمون"},
    "tilapia":               {"calories": 128, "state": "cooked", "ar": "سمك بلطي"},
    "shrimp":                {"calories": 99,  "state": "cooked", "ar": "روبيان"},
    "tuna":                  {"calories": 132, "state": "cooked", "ar": "تونة"},
    "egg":                   {"calories": 155, "state": "cooked", "ar": "بيض"},
    "tofu":                  {"calories": 76,  "state": "raw",    "ar": "توفو"},

    # 🌾 Grains - Raw
    "rice (raw)":            {"calories": 365, "state": "raw",    "ar": "أرز (نيئ)"},
    "oats (raw)":            {"calories": 389, "state": "raw",    "ar": "شوفان (نيئ)"},
    "quinoa (raw)":          {"calories": 368, "state": "raw",    "ar": "كينوا (نيئة)"},
    "bulgur (raw)":          {"calories": 342, "state": "raw",    "ar": "برغل (نيئ)"},
    "couscous (raw)":        {"calories": 376, "state": "raw",    "ar": "كسكسي (نيئ)"},
    "spaghetti (raw)":       {"calories": 371, "state": "raw",    "ar": "سباغيتي (نيئة)"},
    "noodles (raw)":         {"calories": 138, "state": "raw",    "ar": "نودلز (نيئة)"},
    "wheat bran":            {"calories": 216, "state": "raw",    "ar": "نخالة قمح"},
    "soya":                  {"calories": 446, "state": "raw",    "ar": "صويا"},

    # 🌾 Grains - Cooked
    "rice (cooked)":         {"calories": 130, "state": "cooked", "ar": "أرز (مطبوخ)"},
    "oats (cooked)":         {"calories": 68,  "state": "cooked", "ar": "شوفان (مطبوخ)"},
    "quinoa (cooked)":       {"calories": 120, "state": "cooked", "ar": "كينوا (مطبوخة)"},
    "bulgur (cooked)":       {"calories": 83,  "state": "cooked", "ar": "برغل (مطبوخ)"},
    "couscous (cooked)":     {"calories": 112, "state": "cooked", "ar": "كسكسي (مطبوخ)"},
    "spaghetti (cooked)":    {"calories": 158, "state": "cooked", "ar": "سباغيتي (مطبوخة)"},
    "jareesh (cooked)":      {"calories": 95,  "state": "cooked", "ar": "جريش (مطبوخ)"},

    # 🍞 Bread
    "bread (white)":         {"calories": 265, "state": "raw",    "ar": "خبز أبيض"},
    "bread (brown)":         {"calories": 247, "state": "raw",    "ar": "خبز أسمر"},
    "saj bread":             {"calories": 290, "state": "raw",    "ar": "خبز صاج"},
    "toast (white)":         {"calories": 265, "state": "raw",    "ar": "توست أبيض"},
    "croissant":             {"calories": 406, "state": "raw",    "ar": "كرواسون"},
    "donut":                 {"calories": 452, "state": "raw",    "ar": "دونات"},
    "crackers":              {"calories": 450, "state": "raw",    "ar": "بسكويت مالح"},
    "chapati":               {"calories": 410, "state": "raw",    "ar": "شابورة"},

    # 🫘 Legumes - Raw
    "chickpeas (raw)":       {"calories": 364, "state": "raw",    "ar": "حمص (نيئ)"},
    "lentils (raw)":         {"calories": 353, "state": "raw",    "ar": "عدس (نيئ)"},
    "white beans (raw)":     {"calories": 333, "state": "raw",    "ar": "فاصولياء بيضاء (نيئة)"},
    "red beans (raw)":       {"calories": 333, "state": "raw",    "ar": "فاصولياء حمراء (نيئة)"},
    "lupini beans (raw)":    {"calories": 371, "state": "raw",    "ar": "ترمس (نيئ)"},
    "fava beans (raw)":      {"calories": 341, "state": "raw",    "ar": "فول (نيئ)"},

    # 🫘 Legumes - Cooked
    "chickpeas (cooked)":    {"calories": 164, "state": "cooked", "ar": "حمص (مسلوق)"},
    "lentils (cooked)":      {"calories": 116, "state": "cooked", "ar": "عدس (مطبوخ)"},
    "white beans (cooked)":  {"calories": 139, "state": "cooked", "ar": "فاصولياء بيضاء (مسلوقة)"},
    "red beans (cooked)":    {"calories": 127, "state": "cooked", "ar": "فاصولياء حمراء (مسلوقة)"},
    "lupini beans (cooked)": {"calories": 119, "state": "cooked", "ar": "ترمس (مسلوق)"},
    "fava beans (cooked)":   {"calories": 110, "state": "cooked", "ar": "فول (مدمس)"},
    "mixed legumes":         {"calories": 140, "state": "cooked", "ar": "بقوليات مشكلة"},
    "peas":                  {"calories": 81,  "state": "cooked", "ar": "بازلاء"},
    "green beans":           {"calories": 88,  "state": "cooked", "ar": "فول أخضر"},

    # 🥑 Fats & Oils
    "olive oil":             {"calories": 884, "state": "raw",    "ar": "زيت زيتون"},
    "corn oil":              {"calories": 884, "state": "raw",    "ar": "زيت ذرة"},
    "butter":                {"calories": 717, "state": "raw",    "ar": "زبدة"},
    "ghee":                  {"calories": 900, "state": "raw",    "ar": "سمن حيواني"},
    "mayonnaise":            {"calories": 680, "state": "raw",    "ar": "مايونيز"},
    "tahini":                {"calories": 595, "state": "raw",    "ar": "طحينة"},
    "peanut butter":         {"calories": 588, "state": "raw",    "ar": "زبدة فول سوداني"},
    "avocado":               {"calories": 160, "state": "raw",    "ar": "أفوكادو"},

    # 🥜 Nuts & Seeds
    "almonds":               {"calories": 579, "state": "raw",    "ar": "لوز"},
    "walnuts":               {"calories": 654, "state": "raw",    "ar": "جوز"},
    "pistachios":            {"calories": 562, "state": "raw",    "ar": "فستق"},
    "cashews":               {"calories": 553, "state": "raw",    "ar": "كاجو"},
    "hazelnuts":             {"calories": 628, "state": "raw",    "ar": "بندق"},
    "coconut":               {"calories": 354, "state": "raw",    "ar": "جوز هند"},
    "sunflower seeds":       {"calories": 584, "state": "raw",    "ar": "بذور عباد الشمس"},
    "pumpkin seeds":         {"calories": 559, "state": "raw",    "ar": "بذور القرع"},
    "flaxseeds":             {"calories": 534, "state": "raw",    "ar": "بذور الكتان"},
    "chia seeds":            {"calories": 486, "state": "raw",    "ar": "بذور الشيا"},

    # 🍎 Fruits
    "apple":                 {"calories": 52,  "state": "raw",    "ar": "تفاح"},
    "banana":                {"calories": 89,  "state": "raw",    "ar": "موز"},
    "date":                  {"calories": 277, "state": "raw",    "ar": "تمر"},
    "strawberry":            {"calories": 32,  "state": "raw",    "ar": "فراولة"},
    "orange":                {"calories": 47,  "state": "raw",    "ar": "برتقال"},
    "grapes":                {"calories": 69,  "state": "raw",    "ar": "عنب"},
    "mango":                 {"calories": 60,  "state": "raw",    "ar": "مانجو"},
    "watermelon":            {"calories": 30,  "state": "raw",    "ar": "بطيخ"},
    "blackberry":            {"calories": 43,  "state": "raw",    "ar": "توت أسود"},
    "blueberry":             {"calories": 57,  "state": "raw",    "ar": "توت أزرق"},
    "cherry":                {"calories": 50,  "state": "raw",    "ar": "كرز"},
    "pear":                  {"calories": 57,  "state": "raw",    "ar": "كمثرى"},
    "peach":                 {"calories": 39,  "state": "raw",    "ar": "خوخ"},
    "apricot":               {"calories": 48,  "state": "raw",    "ar": "مشمش"},
    "fig":                   {"calories": 74,  "state": "raw",    "ar": "تين"},
    "dried fig":             {"calories": 249, "state": "raw",    "ar": "تين مجفف"},
    "raisins":               {"calories": 299, "state": "raw",    "ar": "زبيب"},
    "pineapple":             {"calories": 50,  "state": "raw",    "ar": "أناناس"},
    "kiwi":                  {"calories": 61,  "state": "raw",    "ar": "كيوي"},
    "pomegranate":           {"calories": 83,  "state": "raw",    "ar": "رمان"},
    "lemon":                 {"calories": 29,  "state": "raw",    "ar": "ليمون"},
    "grapefruit":            {"calories": 42,  "state": "raw",    "ar": "جريب فروت"},

    # 🥦 Vegetables
    "broccoli":              {"calories": 34,  "state": "raw",    "ar": "بروكلي"},
    "cucumber":              {"calories": 15,  "state": "raw",    "ar": "خيار"},
    "tomato":                {"calories": 18,  "state": "raw",    "ar": "طماطم"},
    "spinach":               {"calories": 23,  "state": "raw",    "ar": "سبانخ"},
    "potato (boiled)":       {"calories": 87,  "state": "cooked", "ar": "بطاطس (مسلوقة)"},
    "sweet potato":          {"calories": 86,  "state": "cooked", "ar": "بطاطا حلوة"},
    "bell pepper":           {"calories": 31,  "state": "raw",    "ar": "فلفل رومي"},
    "zucchini":              {"calories": 17,  "state": "raw",    "ar": "كوسا"},
    "eggplant":              {"calories": 25,  "state": "raw",    "ar": "باذنجان"},
    "cauliflower":           {"calories": 25,  "state": "raw",    "ar": "قرنبيط"},
    "cabbage":               {"calories": 25,  "state": "raw",    "ar": "ملفوف"},
    "lettuce":               {"calories": 15,  "state": "raw",    "ar": "خس"},
    "arugula":               {"calories": 25,  "state": "raw",    "ar": "جرجير"},
    "parsley":               {"calories": 36,  "state": "raw",    "ar": "بقدونس"},
    "garlic":                {"calories": 149, "state": "raw",    "ar": "ثوم"},
    "onion":                 {"calories": 40,  "state": "raw",    "ar": "بصل"},
    "carrot":                {"calories": 41,  "state": "raw",    "ar": "جزر"},
    "mushroom":              {"calories": 22,  "state": "raw",    "ar": "فطر"},
    "radish":                {"calories": 16,  "state": "raw",    "ar": "فجل"},
    "turnip":                {"calories": 28,  "state": "raw",    "ar": "لفت"},
    "beetroot":              {"calories": 43,  "state": "raw",    "ar": "شمندر"},
    "okra":                  {"calories": 33,  "state": "raw",    "ar": "بامية"},
    "molokhia":              {"calories": 35,  "state": "raw",    "ar": "ملوخية"},
    "corn":                  {"calories": 86,  "state": "raw",    "ar": "ذرة"},
    "black olives":          {"calories": 115, "state": "raw",    "ar": "زيتون أسود"},
    "green olives":          {"calories": 145, "state": "raw",    "ar": "زيتون أخضر"},

    # 🥛 Dairy
    "milk":                  {"calories": 61,  "state": "raw",    "ar": "حليب"},
    "yogurt":                {"calories": 59,  "state": "raw",    "ar": "زبادي"},
    "cheese (cheddar)":      {"calories": 403, "state": "raw",    "ar": "جبنة شيدر"},
    "cheese (feta)":         {"calories": 264, "state": "raw",    "ar": "جبنة فيتا"},
    "cheese (mozzarella)":   {"calories": 280, "state": "raw",    "ar": "جبنة موزاريلا"},
    "cheese (cottage)":      {"calories": 98,  "state": "raw",    "ar": "جبنة قريش"},
    "labneh":                {"calories": 154, "state": "raw",    "ar": "لبنة"},
    "cream":                 {"calories": 245, "state": "raw",    "ar": "قشطة"},
    "condensed milk":        {"calories": 322, "state": "raw",    "ar": "حليب مكثف"},
    "cooking cream":         {"calories": 195, "state": "raw",    "ar": "كريمة طبخ"},
    "ice cream (vanilla)":   {"calories": 207, "state": "raw",    "ar": "آيس كريم فانيليا"},
    "almond milk":           {"calories": 15,  "state": "raw",    "ar": "حليب لوز"},
    "soy milk":              {"calories": 33,  "state": "raw",    "ar": "حليب صويا"},

    # 🍫 Sweets & Condiments
    "honey":                 {"calories": 304, "state": "raw",    "ar": "عسل"},
    "white sugar":           {"calories": 387, "state": "raw",    "ar": "سكر أبيض"},
    "jam":                   {"calories": 250, "state": "raw",    "ar": "مربى"},
    "date molasses":         {"calories": 290, "state": "raw",    "ar": "دبس تمر"},
    "dark chocolate":        {"calories": 546, "state": "raw",    "ar": "شوكولاتة داكنة"},
    "cocoa powder":          {"calories": 228, "state": "raw",    "ar": "كاكاو بودرة"},
    "plain cake":            {"calories": 297, "state": "raw",    "ar": "كيك سادة"},
    "ketchup":               {"calories": 112, "state": "raw",    "ar": "كاتشب"},
    "mustard":               {"calories": 66,  "state": "raw",    "ar": "خردل"},
    "vinegar":               {"calories": 18,  "state": "raw",    "ar": "خل"},
    "tomato sauce":          {"calories": 82,  "state": "raw",    "ar": "صلصة طماطم"},
    "chicken stock cube":    {"calories": 198, "state": "raw",    "ar": "مكعب مرقة دجاج"},
    "potato chips":          {"calories": 536, "state": "raw",    "ar": "شيبس بطاطس"},
    "popcorn (no oil)":      {"calories": 387, "state": "raw",    "ar": "فشار بدون زيت"},
}